name: $name
version: $version
main: lee.code.villagers.Villagers
description: $description
author: Lee
folia-supported: true
api-version: "$apiVersion"
commands:
  villager:
    description: Main villager npc command.
    permission: villagers.command.villager
    aliases: [t]
